package hook

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"yomirelay/internal/games"
)

func TestRenderIncludesOwnershipAndGameMetadata(t *testing.T) {
	content, err := Render("111", "影の物語")
	if err != nil {
		t.Fatal(err)
	}
	text := string(content)
	for _, required := range []string{"# Generated by YomiRelay", "# DO NOT EDIT", "config.all_character_callbacks.append", "127.0.0.1", "17322", `YOMIRELAY_GAME_NAME = "影の物語"`} {
		if !strings.Contains(text, required) {
			t.Errorf("rendered hook missing %q: %s", required, text)
		}
	}
}

func TestInstallCreatesAndUpdatesManagedHook(t *testing.T) {
	game := testGame(t)
	manager := Manager{}
	path, err := manager.HookPath(game)
	if err != nil {
		t.Fatal(err)
	}
	if err := manager.Install(game); err != nil {
		t.Fatal(err)
	}
	first, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !manager.Installed(game) {
		t.Fatal("managed hook not reported installed")
	}
	if err := os.WriteFile(path, []byte("# Generated by YomiRelay\n# DO NOT EDIT\nold"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := manager.Install(game); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) || !strings.Contains(string(second), "config.all_character_callbacks.append") {
		t.Fatal("managed hook was not updated")
	}
}

func TestInstallRefusesUnmanagedConflict(t *testing.T) {
	game := testGame(t)
	path := filepath.Join(game.InstallPath, "game", "_yomirelay_hook.rpy")
	original := []byte("init python: pass\n")
	if err := os.WriteFile(path, original, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := (Manager{}).Install(game); !errors.Is(err, ErrFileConflict) {
		t.Fatalf("Install error = %v, want ErrFileConflict", err)
	}
	got, _ := os.ReadFile(path)
	if string(got) != string(original) {
		t.Fatal("unmanaged file was modified")
	}
}

func TestRemoveDeletesOnlyManagedHook(t *testing.T) {
	game := testGame(t)
	manager := Manager{}
	if err := manager.Install(game); err != nil {
		t.Fatal(err)
	}
	if err := manager.Remove(game); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(game.InstallPath, "game", "_yomirelay_hook.rpy")); !os.IsNotExist(err) {
		t.Fatalf("hook still exists, stat error = %v", err)
	}
}

func TestRemoveRefusesUnmanagedHook(t *testing.T) {
	game := testGame(t)
	path := filepath.Join(game.InstallPath, "game", "_yomirelay_hook.rpy")
	original := []byte("init python: pass\n")
	if err := os.WriteFile(path, original, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := (Manager{}).Remove(game); !errors.Is(err, ErrNotManaged) {
		t.Fatalf("Remove error = %v, want ErrNotManaged", err)
	}
	got, _ := os.ReadFile(path)
	if string(got) != string(original) {
		t.Fatal("unmanaged file was removed")
	}
}

func TestInstallRefusesGameDirectorySymlinkOutsideInstall(t *testing.T) {
	install := t.TempDir()
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(install, "game")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	game := games.Game{AppID: "111", Name: "Game", InstallPath: install, Engine: "renpy"}
	if err := (Manager{}).Install(game); !errors.Is(err, ErrUnsafePath) {
		t.Fatalf("Install error = %v, want ErrUnsafePath", err)
	}
	if _, err := os.Stat(filepath.Join(outside, "_yomirelay_hook.rpy")); !os.IsNotExist(err) {
		t.Fatal("hook was created through game symlink")
	}
}

func TestInstallRefusesHookSymlink(t *testing.T) {
	game := testGame(t)
	path := filepath.Join(game.InstallPath, "game", "_yomirelay_hook.rpy")
	outside := filepath.Join(t.TempDir(), "outside.rpy")
	if err := os.WriteFile(outside, []byte("untouched"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, path); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := (Manager{}).Install(game); !errors.Is(err, ErrUnsafePath) {
		t.Fatalf("Install error = %v, want ErrUnsafePath", err)
	}
	got, _ := os.ReadFile(outside)
	if string(got) != "untouched" {
		t.Fatal("hook symlink target was modified")
	}
}

func testGame(t *testing.T) games.Game {
	t.Helper()
	install := t.TempDir()
	if err := os.Mkdir(filepath.Join(install, "game"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(install, "renpy"), 0o755); err != nil {
		t.Fatal(err)
	}
	return games.Game{AppID: "111", Name: "Game", InstallPath: install, Engine: "renpy"}
}
