package hook

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"yomirelay/internal/games"
)

var (
	ErrSourceUnavailable = errors.New("native dialogue hook is not available; no game files were changed")
	ErrFileConflict      = errors.New("hook file exists but is not managed by YomiRelay")
	ErrNotManaged        = errors.New("hook file is not managed by YomiRelay")
	ErrUnsafePath        = errors.New("unsafe hook path")
)

type Manager struct{}

func (Manager) HookPath(game games.Game) (string, error) {
	if game.Engine != "renpy" || filepath.Clean(game.InstallPath) == "." {
		return "", ErrUnsafePath
	}
	installRoot, err := filepath.Abs(filepath.Clean(game.InstallPath))
	if err != nil {
		return "", fmt.Errorf("%w: resolve install path: %v", ErrUnsafePath, err)
	}
	installRoot, err = filepath.EvalSymlinks(installRoot)
	if err != nil {
		return "", fmt.Errorf("%w: resolve install path: %v", ErrUnsafePath, err)
	}
	rootInfo, err := os.Stat(installRoot)
	if err != nil || !rootInfo.IsDir() {
		return "", fmt.Errorf("%w: install path is not a directory", ErrUnsafePath)
	}
	gamePath := filepath.Join(installRoot, "game")
	gameInfo, err := os.Lstat(gamePath)
	if err != nil || !gameInfo.IsDir() || gameInfo.Mode()&os.ModeSymlink != 0 {
		return "", fmt.Errorf("%w: game directory is unsafe", ErrUnsafePath)
	}
	resolvedGame, err := filepath.EvalSymlinks(gamePath)
	if err != nil {
		return "", fmt.Errorf("%w: resolve game directory: %v", ErrUnsafePath, err)
	}
	relative, err := filepath.Rel(installRoot, resolvedGame)
	if err != nil || relative != "game" {
		return "", ErrUnsafePath
	}
	return filepath.Join(gamePath, "_yomirelay_hook.rpy"), nil
}

func (m Manager) Installed(game games.Game) bool {
	path, err := m.HookPath(game)
	if err != nil {
		return false
	}
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	return err == nil && managed(data)
}

func (m Manager) Install(game games.Game) error {
	if game.Engine == "nexas" {
		return ErrSourceUnavailable
	}
	path, err := m.HookPath(game)
	if err != nil {
		return err
	}
	if info, statErr := os.Lstat(path); statErr == nil {
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			return ErrUnsafePath
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if !managed(data) {
			return ErrFileConflict
		}
	} else if !os.IsNotExist(statErr) {
		return statErr
	}
	content, err := Render(game.AppID, game.Name)
	if err != nil {
		return err
	}
	directory := filepath.Dir(path)
	temporary, err := os.CreateTemp(directory, ".yomirelay-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return err
	}
	return nil
}

func (m Manager) Remove(game games.Game) error {
	if game.Engine == "nexas" {
		return ErrSourceUnavailable
	}
	path, err := m.HookPath(game)
	if err != nil {
		return err
	}
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return ErrUnsafePath
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !managed(data) {
		return ErrNotManaged
	}
	return os.Remove(path)
}

func managed(data []byte) bool {
	text := string(data)
	return strings.Contains(text, "# Generated by YomiRelay") && strings.Contains(text, "# DO NOT EDIT")
}
