package hook

import (
	"encoding/json"
	"fmt"
	"strconv"
)

const hookPrefix = `# Generated by YomiRelay
# DO NOT EDIT

`

const hookBody = `init python:
    import json
    import socket
    import time

    YOMIRELAY_GAME_ID = %s
    YOMIRELAY_GAME_NAME = %s

    try:
        _yomirelay_text_type = unicode
    except NameError:
        _yomirelay_text_type = str

    def _yomirelay_clean(value):
        result = []
        index = 0
        while index < len(value):
            if value[index] == "{" and index + 1 < len(value) and (value[index + 1] == "/" or ("A" <= value[index + 1] <= "Z") or ("a" <= value[index + 1] <= "z") or value[index + 1] == "_"):
                end = value.find("}", index + 2)
                if end >= 0:
                    body = value[index + 1:end]
                    valid = True
                    for character in body:
                        if not (("A" <= character <= "Z") or ("a" <= character <= "z") or ("0" <= character <= "9") or character in "/_=-+.: "):
                            valid = False
                            break
                    if valid:
                        index = end + 1
                        continue
            result.append(value[index])
            index += 1
        return "".join(result)

    def _yomirelay_callback(event, what=None, start=None, **kwargs):
        try:
            if event != "show" or start != 0:
                return
            text = _yomirelay_clean(what or "")
            if not text:
                return
            packet = {"v": 1, "gameId": YOMIRELAY_GAME_ID,
                      "gameName": YOMIRELAY_GAME_NAME, "text": text,
                      "timestamp": int(time.time())}
            if kwargs.get("who"):
                packet["speaker"] = kwargs["who"]
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.setblocking(0)
            encoded = json.dumps(packet, ensure_ascii=False)
            if isinstance(encoded, _yomirelay_text_type):
                encoded = encoded.encode("utf-8")
            sock.sendto(encoded, ("127.0.0.1", 17322))
            sock.close()
        except Exception:
            pass

    config.all_character_callbacks.append(_yomirelay_callback)
`

// Render returns an ownership-marked, Python 2/3-compatible Ren'Py callback hook.
func Render(appID, gameName string) ([]byte, error) {
	id, err := json.Marshal(appID)
	if err != nil {
		return nil, fmt.Errorf("marshal game ID: %w", err)
	}
	if _, err := json.Marshal(gameName); err != nil {
		return nil, fmt.Errorf("marshal game name: %w", err)
	}
	// JSON permits UTF-8, but ASCII escapes keep the generated source valid for
	// Python 2 runtimes, which do not assume an encoding for source files.
	nameLiteral := "u" + strconv.QuoteToASCII(gameName)
	return []byte(hookPrefix + fmt.Sprintf(hookBody, id, nameLiteral)), nil
}
